apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
  labels:
    app: cache
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      name: cache
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: memcached
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  type: ClusterIP
  selector:
    app: cache
  ports:
  - port: 11211
    targetPort: 11211
